version: '2'
services:

  gui:
    image: latex-gui
    ports:
      - "80:3000"
    volumes:
      - .:/data

  server:
    image: latex-server
    ports:
      - "3001:3001"
    volumes:
      - .:/data
